language: php
php:
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester tests -s

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   stage: Code Standard Checker
            php: 7.1
            install:
                # Install Nette Code Checker
                - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
                # Install Nette Coding Standard
                - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress

            script:
                - php temp/code-checker/code-checker
                - php temp/coding-standard/ecs check src tests --config tests/coding-standard.yml


        -   stage: Code Coverage
            php: 7.1
            script:
                - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml


    allow_failures:
        -   php: 7.2
        -   stage: Code Coverage


sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
