language: php
php:
    - 7.0
    - 7.1
    - 7.2

env:
matrix:
    include:
        - php: 7.0
          env: coverage=on
        - php: 7.1
          env: codingStandard=on

    allow_failures:
        - php: 7.0
          env: coverage=on
        - php: 7.2

script:
    - vendor/bin/tester tests -s -c tests/php-unix.ini $coverageArgs
    - >
      if [ "$codingStandard" ]; then
      php temp/code-checker/src/code-checker.php --short-arrays --strict-types -i tests/Utils/fixtures.reflection
      && php temp/coding-standard/ecs check src tests --config tests/coding-standard.neon;
      fi

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

before_script:
    # Install Nette Tester
    - travis_retry composer install --no-interaction --prefer-dist
    # Install Code Checkers
    - >
      if [ "$codingStandard" ]; then
      travis_retry composer create-project nette/code-checker temp/code-checker ~2 --no-interaction;
      travis_retry composer create-project nette/coding-standard temp/coding-standard --no-interaction;
      fi
    - if [ "$coverage" ]; then coverageArgs="-p phpdbg --coverage ./coverage.xml --coverage-src ./src"; fi

after_script:
    # Report Code Coverage
    - >
      if [ "$coverage" ]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config tests/.coveralls.yml;
      fi

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
