language: php
php:
    - 7.1
    - 7.2

before_install:
    # turn off XDebug
    - phpenv config-rm xdebug.ini || return 0

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester tests -s

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
    include:
        -   stage: Code Standard Checker
            php: 7.1
            install:
                # Install Nette Code Checker
                - travis_retry composer create-project nette/code-checker temp/code-checker ~2 --no-progress
                # Install Nette Coding Standard
                - travis_retry composer create-project nette/coding-standard temp/coding-standard --no-progress

            script:
                - php temp/code-checker/src/code-checker.php --short-arrays --strict-types -i tests/Utils/fixtures.reflection
                - php temp/coding-standard/ecs check src tests --config tests/coding-standard.neon


        -   stage: Static Analysis
            php: 7.1
            install:
                # Install PHPStan
                - travis_retry composer create-project phpstan/phpstan-shim temp/phpstan --no-progress
                - travis_retry composer install --no-progress --prefer-dist

            script:
                - php temp/phpstan/phpstan.phar analyse --autoload-file vendor/autoload.php --level 7 --configuration tests/phpstan.neon src


        -   stage: Code Coverage
            script:
                - vendor/bin/tester -p phpdbg tests -s --coverage ./coverage.xml --coverage-src ./src
            after_script:
                - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
                - php coveralls.phar --verbose --config tests/.coveralls.yml


    allow_failures:
        -   stage: Static Analysis
        -   stage: Code Coverage


sudo: false

cache:
    directories:
        - $HOME/.composer/cache

notifications:
    email: false
